import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "David Nakeeran",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.variable} antialiased min-h-dvh`}>
        <div className="max-w-7xl mx-auto flex flex-col lg:flex-row lg:items-start lg:min-h-dvh w-full gap-8 px-6">
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
